spring:
  application:
    name: spring-boot-kotlin-oauth2-github
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: xxxx
            client-secret: xxxx
